<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Madplan.Core\Madplan.Core.csproj" />
    <ProjectReference Include="..\Madplan.Data\Madplan.Data.csproj" />
    <ProjectReference Include="..\Madplan.Nemlig\Madplan.Nemlig.csproj" />
    <ProjectReference Include="..\Madplan.Recipes\Madplan.Recipes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <InternalsVisibleTo Include="Madplan.Tests" />
  </ItemGroup>
</Project>
