import {
  type Candidate,
  type ParsedCharacter,
  type SimSettings,
  SLOT_TOKENS,
  type SlotToken,
} from "./types";

/**
 * Header options shared by every profile in one comparison, so all setups
 * are simmed under identical encounter conditions.
 *
 * Option names verified against SimulationCraft 1210-01 sources
 * (engine/sim/sim.cpp): fight_style, max_time, desired_targets,
 * optimal_raid, iterations, threads, report_details, json2.
 */
export function simHeader(settings: SimSettings, iterations: number): string[] {
  return [
    `iterations=${iterations}`,
    `threads=${settings.threads}`,
    `fight_style=${settings.fightStyle}`,
    `max_time=${settings.durationSeconds}`,
    `desired_targets=${settings.targets}`,
    "optimal_raid=1",
    "report_details=0",
  ];
}

/** Slots ordered as SimC expects them; used for deterministic output. */
const SLOT_ORDER: SlotToken[] = [...SLOT_TOKENS];

export function baseProfileLines(parsed: ParsedCharacter): string[] {
  const lines = [...parsed.charLines];
  for (const slot of SLOT_ORDER) {
    const item = parsed.equipped[slot];
    if (item) lines.push(`${slot}=${item.simcString}`);
  }
  return lines;
}

/**
 * A profileset line assigning a slot. An empty right-hand side clears the
 * slot, which is how a two-hander removes the off-hand.
 */
export function candidateLines(candidate: Candidate): string[] {
  const sorted = [...candidate.overrides].sort(
    (a, b) => SLOT_ORDER.indexOf(a.slot) - SLOT_ORDER.indexOf(b.slot),
  );
  return sorted.map(
    (o, idx) =>
      `profileset."${candidate.id}"${idx === 0 ? "=" : "+="}${o.slot}=${
        o.item ? o.item.simcString : ""
      }`,
  );
}

/** Build a full .simc file: header, character profile, then profilesets. */
export function buildProfile(
  parsed: ParsedCharacter,
  settings: SimSettings,
  iterations: number,
  candidates: Candidate[],
): string {
  const parts = [
    "# Generated by PAPI gear optimizer — every setup below is simulated by SimulationCraft.",
    ...simHeader(settings, iterations),
    "",
    ...baseProfileLines(parsed),
  ];
  if (candidates.length > 0) {
    parts.push("");
    for (const candidate of candidates) parts.push(...candidateLines(candidate));
  }
  return `${parts.join("\n")}\n`;
}
